# === Логирование ===
log:
  version: 1
  disable_existing_loggers: True
  
  formatters:

    standard:
      format: '%(asctime)s %(name)12s [%(levelname)8s]: %(message)s'

    short_console:
      format: '%(asctime)s %(name)12s: %(message)s'

    just_message:
      format: '%(message)s'

  handlers:
    console:
      level: DEBUG
      formatter: standard
      class: logging.StreamHandler
      stream: ext://sys.stdout  # Default is stderr

    short_console:
      level: INFO
      formatter: just_message
      class: logging.StreamHandler
      stream: ext://sys.stdout  # Default is stderr

# -- Логгеры --
  loggers:
    '':
      handlers: [short_console]
      level: ERROR

    __main__:
      handlers: [short_console]
      level: ERROR

    env.trade_env:
      propagate: False
      level: INFO

    core.core:
      handlers: [short_console]
      propagate: False
      level: ERROR

    rl.dqn:
      handlers: [short_console]
      propagate: False
      level: WARNING

    data_point.train_dp_factory:
      handlers: [console]
      propagate: False
      level: ERROR

    core.actions.trade_action:
      handlers: [console]
      propagate: False
      level: ERROR

    

    